<template>
  <div class="system-settings">
    <div class="settings-header">
      <h1>⚙️ System Settings</h1>
      <p>Configure system-wide settings and preferences</p>
    </div>

    <div class="settings-content">
      <div class="settings-section">
        <h2>General Settings</h2>
        <div class="settings-card">
          <div class="setting-item">
            <label>Application Name</label>
            <input type="text" v-model="settings.appName" class="form-input" />
          </div>
          <div class="setting-item">
            <label>Default Academic Period</label>
            <select v-model="settings.defaultPeriod" class="form-select">
              <option value="">Select Period</option>
              <option value="quarter">Quarter</option>
              <option value="semester">Semester</option>
              <option value="trimester">Trimester</option>
            </select>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2>Assessment Settings</h2>
        <div class="settings-card">
          <div class="setting-item">
            <label>
              <input type="checkbox" v-model="settings.allowRetakes" />
              Allow Assessment Retakes
            </label>
          </div>
          <div class="setting-item">
            <label>
              <input type="checkbox" v-model="settings.autoGrade" />
              Auto-grade Assessments
            </label>
          </div>
          <div class="setting-item">
            <label>Default Time Limit (minutes)</label>
            <input type="number" v-model.number="settings.defaultTimeLimit" class="form-input" min="1" max="180" />
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2>Question Generation Settings</h2>
        <div class="settings-card">
          <div class="setting-item">
            <label>Question Generation Method</label>
            <select v-model="settings.questionGenerationMethod" class="form-select">
              <option value="template">Template-Based (Fast, Free, Recommended)</option>
              <option value="hybrid">Hybrid (Templates + AI Fallback)</option>
              <option value="ai-gemini">AI: Google Gemini</option>
              <option value="ai-openai">AI: OpenAI GPT</option>
            </select>
            <p class="setting-description">
              <strong>Template:</strong> Uses hard-coded templates for common goal patterns. Fast and free.<br>
              <strong>Hybrid:</strong> Uses templates first, falls back to AI for complex goals.<br>
              <strong>AI Options:</strong> All questions generated by AI (requires API keys).
            </p>
          </div>
          <div v-if="settings.questionGenerationMethod === 'ai-gemini' || settings.questionGenerationMethod === 'hybrid'" class="setting-item">
            <label>Google Gemini API Key</label>
            <input 
              type="password" 
              v-model="settings.geminiApiKey" 
              class="form-input" 
              placeholder="Enter Gemini API key (or set VITE_GEMINI_API_KEY)"
            />
            <p class="setting-description">
              Get your API key from <a href="https://makersuite.google.com/app/apikey" target="_blank">Google AI Studio</a>
            </p>
          </div>
          <div v-if="settings.questionGenerationMethod === 'ai-openai' || settings.questionGenerationMethod === 'hybrid'" class="setting-item">
            <label>OpenAI API Key</label>
            <input 
              type="password" 
              v-model="settings.openaiApiKey" 
              class="form-input" 
              placeholder="Enter OpenAI API key (or set VITE_OPENAI_API_KEY)"
            />
            <p class="setting-description">
              Get your API key from <a href="https://platform.openai.com/api-keys" target="_blank">OpenAI Platform</a>
            </p>
          </div>
          <div v-if="settings.questionGenerationMethod === 'hybrid'" class="setting-item">
            <label>
              <input type="checkbox" v-model="settings.useAIIfTemplateFails" />
              Use AI if template generation fails
            </label>
            <p class="setting-description">
              When enabled, AI will be used if template generation produces a default/fallback question
            </p>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2>Notification Settings</h2>
        <div class="settings-card">
          <div class="setting-item">
            <label>
              <input type="checkbox" v-model="settings.emailNotifications" />
              Enable Email Notifications
            </label>
          </div>
          <div class="setting-item">
            <label>
              <input type="checkbox" v-model="settings.assessmentReminders" />
              Send Assessment Reminders
            </label>
          </div>
        </div>
      </div>

      <div class="settings-actions">
        <button @click="saveSettings" class="btn-primary" :disabled="saving">
          {{ saving ? 'Saving...' : 'Save Settings' }}
        </button>
        <button @click="resetSettings" class="btn-secondary">
          Reset to Defaults
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';

const settings = ref({
  appName: 'Jepson Math Assessments',
  defaultPeriod: '',
  allowRetakes: true,
  autoGrade: true,
  defaultTimeLimit: 30,
  questionGenerationMethod: 'template' as 'template' | 'hybrid' | 'ai-gemini' | 'ai-openai',
  geminiApiKey: '',
  openaiApiKey: '',
  useAIIfTemplateFails: false,
  emailNotifications: true,
  assessmentReminders: true
});

const saving = ref(false);

const saveSettings = async () => {
  saving.value = true;
  try {
    // TODO: Implement settings save to Firestore
    console.log('Saving settings:', settings.value);
    await new Promise(resolve => setTimeout(resolve, 500)); // Simulate API call
    alert('Settings saved successfully!');
  } catch (error) {
    console.error('Error saving settings:', error);
    alert('Failed to save settings. Please try again.');
  } finally {
    saving.value = false;
  }
};

const resetSettings = () => {
  if (confirm('Are you sure you want to reset all settings to defaults?')) {
    settings.value = {
      appName: 'Jepson Math Assessments',
      defaultPeriod: '',
      allowRetakes: true,
      autoGrade: true,
      defaultTimeLimit: 30,
      questionGenerationMethod: 'template',
      geminiApiKey: '',
      openaiApiKey: '',
      useAIIfTemplateFails: false,
      emailNotifications: true,
      assessmentReminders: true
    };
  }
};

onMounted(() => {
  // TODO: Load settings from Firestore
});
</script>

<style scoped>
.system-settings {
  max-width: 1000px;
  margin: 0 auto;
  padding: 20px;
}

.settings-header {
  text-align: center;
  margin-bottom: 40px;
}

.settings-header h1 {
  color: #1f2937;
  font-size: 2.5rem;
  margin-bottom: 10px;
}

.settings-header p {
  color: #6b7280;
  font-size: 1.1rem;
}

.settings-section {
  margin-bottom: 30px;
}

.settings-section h2 {
  color: #1f2937;
  font-size: 1.5rem;
  margin-bottom: 15px;
}

.settings-card {
  background: white;
  border-radius: 12px;
  padding: 25px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.setting-item {
  margin-bottom: 20px;
}

.setting-item:last-child {
  margin-bottom: 0;
}

.setting-item label {
  display: block;
  color: #374151;
  font-weight: 500;
  margin-bottom: 8px;
}

.setting-item input[type="checkbox"] {
  margin-right: 8px;
}

.setting-description {
  margin-top: 8px;
  font-size: 0.875rem;
  color: #6b7280;
  line-height: 1.5;
}

.setting-description a {
  color: #dc2626;
  text-decoration: underline;
}

.setting-description strong {
  color: #374151;
}

.form-input,
.form-select {
  width: 100%;
  padding: 10px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 1rem;
}

.form-input:focus,
.form-select:focus {
  outline: none;
  border-color: #dc2626;
  box-shadow: 0 0 0 3px rgba(220, 38, 38, 0.1);
}

.settings-actions {
  display: flex;
  gap: 15px;
  margin-top: 30px;
}

.btn-primary,
.btn-secondary {
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  border: none;
  font-size: 1rem;
  transition: all 0.2s;
}

.btn-primary {
  background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(220, 38, 38, 0.3);
}

.btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-secondary {
  background: white;
  color: #374151;
  border: 2px solid #d1d5db;
}

.btn-secondary:hover {
  border-color: #9ca3af;
  background: #f9fafb;
}
</style>

